[package]
name = "futil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
html = "0.6.2"
image = "0.24.7"
itertools = "0.11.0"
regex = "1.10.0"
